name: Deploy OMR Checker

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch:  

jobs:
  deploy:
    if: github.event_name == 'push'
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/mediaserver/omrchecker/OMRChecker

    steps:
      - name: Pull latest code
        run: git pull origin main

      - name: Restart service
        run: sudo systemctl restart ctet

  sync_logs:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: self-hosted

    defaults:
      run:
        working-directory: /home/mediaserver/omrchecker/OMRChecker

    steps:
      - name: Push logs CSV
        run: |
          git add outputs/results_logs.csv
          git commit -m "auto: update logs $(date)" || true
          git push origin main